# Stage 1 - build Angular app
FROM node:latest as builder
WORKDIR /app
COPY package.json ./
# RUN npm cache clean --force
RUN yarn install
COPY . .
RUN npm run build
# Stage 2 - run Angular app with Nginx
FROM nginx:latest
COPY --from=builder ./dist/apps/construction /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

