version: '3'
services:
  angular-app:
    build:
      context: ./
      dockerfile: Dockerfile.angular
    ports:
      - '80:80'

  # api:
  #   build:
  #     context: ./apps/api
  #     dockerfile: Dockerfile.api
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - mysql

  # mysql:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.mysql
  #   ports:
  #     - '3306:3306'
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: construction
  #     MYSQL_USER: construction_user
  #     MYSQL_PASSWORD: saeid

  # phpmyadmin:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.phpmyadmin
  #   ports:
  #     - '8080:80'
  #   depends_on:
  #     - mysql
